version: "3.1"

services:
  highlightly-postgres:
    container_name: highlightly-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/data:/usr/local/bin/postgres/data
